modLoader = "javafml"
loaderVersion = "*"
license = "Polyform-Shield-1.0"

[[mods]]
modId = "sodium"

version = "${version}"
displayName = "Sodium"

logoFile="sodium-icon.png" #optional

authors="JellySquid"
# A multi-line description for your mod. This has no minimum length, but it *is* required!
description = '''
Sodium is a free and open-source optimization mod for Minecraft which improves frame rates and reduces lag spikes.
'''

provides = ["indium"]

[modproperties.sodium]
"fabric-renderer-api-v1:contains_renderer"=true
